In [1]:
import pandas as pd
import networkx as nx
import numpy as np
import pickle

import sys
sys.path.append('..')

# Loading Data

In [2]:
df_pre_graphed = pd.read_csv(f"../data_in_processing/E1S1_scaled.csv", index_col=[0, 1])

In [3]:
df_pre_graphed

                           Nuclear_size  ERKKTR_ratio  FoxO3A_ratio  \
Image_Metadata_T track_id
0                1              303.000      0.704407       1.33383
                 2              268.001      1.227760       1.20592
                 3              370.000      0.779226       1.27561
                 4              341.000      0.870780       1.34460
                 5              308.000      0.807262       1.47321
...                                 ...           ...           ...
257              2849           165.000      0.607956       1.31242
                 2850           138.000      0.775133       1.15722
                 2855           148.000      1.114600       1.25315
                 2856           148.000      0.861735       1.16059
                 2857           175.000      0.589269       1.31594

                           objNuclei_Location_Center_X  \
Image_Metadata_T track_id
0                1                             932.211
                 2                             162.328
                 3                             647.816
                 4                             642.988
                 5                             990.718
...                                                ...
257              2849                          839.988
                 2850                         1019.510
                 2855                          411.797
                 2856                         1018.580
                 2857                         1018.850

                           objNuclei_Location_Center_Y  ERKKTR_ratio_scaled  \
Image_Metadata_T track_id
0                1                            875.2480             0.239322
                 2                            365.4140             0.540105
                 3                            846.5760             0.156325
                 4                            827.8650             0.364739
                 5                             59.4675             0.161764
...                                                ...                  ...
257              2849                         877.9760             1.000000
                 2850                          50.1159             0.076820
                 2855                         205.4320             0.040999
                 2856                         809.4530             0.387449
                 2857                         771.6110             0.370075

                           FoxO3A_ratio_scaled
Image_Metadata_T track_id
0                1                    0.614450
                 2                    0.506309
                 3                    0.700809
                 4                    0.657277
                 5                    0.718735
...                                        ...
257              2849                 1.000000
                 2850                 0.356672
                 2855                 0.065812
                 2856                 0.608673
                 2857                 0.948178

[356632 rows x 7 columns]

# Processing Data

In [4]:
from scripts.Mapping_nodes_in_time import calculate_tracks_on_graphs

In [5]:
time_to_trackA_to_trackB_to_stats: dict[int, dict[int, dict[int, dict[str, float]]]] = {}

for image_T in df_pre_graphed.index.get_level_values(0).unique().to_list()[:-1]:
    time_to_trackA_to_trackB_to_stats[image_T] = calculate_tracks_on_graphs(
        image_T, "../data_in_processing/graphs",
        stats_types=["t0", "t1", "diff"]
    )
    print(f"[{image_T}] Done!")

[0] Done!
[1] Done!
[2] Done!
[3] Done!
[4] Done!
[5] Done!
[6] Done!
[7] Done!
[8] Done!
[9] Done!
[10] Done!
[11] Done!
[12] Done!
[13] Done!
[14] Done!
[15] Done!
[16] Done!
[17] Done!
[18] Done!
[19] Done!
[20] Done!
[21] Done!
[22] Done!
[23] Done!
[24] Done!
[25] Done!
[26] Done!
[27] Done!
[28] Done!
[29] Done!
[30] Done!
[31] Done!
[32] Done!
[33] Done!
[34] Done!
[35] Done!
[36] Done!
[37] Done!
[38] Done!
[39] Done!
[40] Done!
[41] Done!
[42] Done!
[43] Done!
[44] Done!
[45] Done!
[46] Done!
[47] Done!
[48] Done!
[49] Done!
[50] Done!
[51] Done!
[52] Done!
[53] Done!
[54] Done!
[55] Done!
[56] Done!
[57] Done!
[58] Done!
[59] Done!
[60] Done!
[61] Done!
[62] Done!
[63] Done!
[64] Done!
[65] Done!
[66] Done!
[67] Done!
[68] Done!
[69] Done!
[70] Done!
[71] Done!
[72] Done!
[73] Done!
[74] Done!
[75] Done!
[76] Done!
[77] Done!
[78] Done!
[79] Done!
[80] Done!
[81] Done!
[82] Done!
[83] Done!
[84] Done!
[85] Done!
[86] Done!
[87] Done!
[88] Done!
[89] Done!
[90] Done!
[91] Done!
[92] Done!
[93] Done!
[94] Done!
[95] Done!
[96] Done!
[97] Done!
[98] Done!
[99] Done!
[100] Done!
[101] Done!
[102] Done!
[103] Done!
[104] Done!
[105] Done!
[106] Done!
[107] Done!
[108] Done!
[109] Done!
[110] Done!
[111] Done!
[112] Done!
[113] Done!
[114] Done!
[115] Done!
[116] Done!
[117] Done!
[118] Done!
[119] Done!
[120] Done!
[121] Done!
[122] Done!
[123] Done!
[124] Done!
[125] Done!
[126] Done!
[127] Done!
[128] Done!
[129] Done!
[130] Done!
[131] Done!
[132] Done!
[133] Done!
[134] Done!
[135] Done!
[136] Done!
[137] Done!
[138] Done!
[139] Done!
[140] Done!
[141] Done!
[142] Done!
[143] Done!
[144] Done!
[145] Done!
[146] Done!
[147] Done!
[148] Done!
[149] Done!
[150] Done!
[151] Done!
[152] Done!
[153] Done!
[154] Done!
[155] Done!
[156] Done!
[157] Done!
[158] Done!
[159] Done!
[160] Done!
[161] Done!
[162] Done!
[163] Done!
[164] Done!
[165] Done!
[166] Done!
[167] Done!
[168] Done!
[169] Done!
[170] Done!
[171] Done!
[172] Done!
[173] Done!
[174] Done!
[175] Done!
[176] Done!
[177] Done!
[178] Done!
[179] Done!
[180] Done!
[181] Done!
[182] Done!
[183] Done!
[184] Done!
[185] Done!
[186] Done!
[187] Done!
[188] Done!
[189] Done!
[190] Done!
[191] Done!
[192] Done!
[193] Done!
[194] Done!
[195] Done!
[196] Done!
[197] Done!
[198] Done!
[199] Done!
[200] Done!
[201] Done!
[202] Done!
[203] Done!
[204] Done!
[205] Done!
[206] Done!
[207] Done!
[208] Done!
[209] Done!
[210] Done!
[211] Done!
[212] Done!
[213] Done!
[214] Done!
[215] Done!
[216] Done!
[217] Done!
[218] Done!
[219] Done!
[220] Done!
[221] Done!
[222] Done!
[223] Done!
[224] Done!
[225] Done!
[226] Done!
[227] Done!
[228] Done!
[229] Done!
[230] Done!
[231] Done!
[232] Done!
[233] Done!
[234] Done!
[235] Done!
[236] Done!
[237] Done!
[238] Done!
[239] Done!
[240] Done!
[241] Done!
[242] Done!
[243] Done!
[244] Done!
[245] Done!
[246] Done!
[247] Done!
[248] Done!
[249] Done!
[250] Done!
[251] Done!
[252] Done!
[253] Done!
[254] Done!
[255] Done!
[256] Done!

In [6]:
flat = {
    (i, j, k): cols
    for i, d1 in time_to_trackA_to_trackB_to_stats.items()
    for j, d2 in d1.items()
    for k, cols in d2.items()
}

df = pd.DataFrame.from_dict(flat, orient="index")
df.index = pd.MultiIndex.from_tuples(df.index, names=["Image_Metadata_T", "track_id_t0", "track_id_t1"])

In [7]:
df

                                          ERK_me_t0  ERK_neigh_t0  ERK_me_t1  \
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495          0.713311      0.008047   0.577748
                             874           0.713311      0.765061   0.577748
                             304           0.713311      0.004324   0.577748
                 1495        1201          0.008047      0.713311   0.002635
                             304           0.008047      0.004324   0.002635
...                                             ...           ...        ...
256              749         778           0.158900      0.255583   0.156758
                             1042          0.158900      0.274962   0.156758
                             2207          0.158900      0.473508   0.156758
                             134           0.158900      0.968972   0.156758
                             1615          0.158900      0.842980   0.156758

                                          ERK_neigh_t1  ERK_me_diff  \
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495             0.002635    -0.135563
                             874              0.802783    -0.135563
                             304              0.020567    -0.135563
                 1495        1201             0.577748    -0.005412
                             304              0.020567    -0.005412
...                                                ...          ...
256              749         778              0.399122    -0.002142
                             1042             0.443283    -0.002142
                             2207             0.417289    -0.002142
                             134              0.936511    -0.002142
                             1615             0.771625    -0.002142

                                          ERK_neigh_diff
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495              -0.005412
                             874                0.037722
                             304                0.016243
                 1495        1201              -0.135563
                             304                0.016243
...                                                  ...
256              749         778                0.143538
                             1042               0.168321
                             2207              -0.056219
                             134               -0.032461
                             1615              -0.071355

[2057644 rows x 6 columns]

In [8]:
df.to_csv(f"../data_in_processing/E1S1_graphs_flattened.csv")