In [2]:
import networkx as nx
import pandas as pd
import numpy as np

import sys
sys.path.append('..')

# Loading Data

In [3]:
clus_id = 3

In [4]:
df_edges_labels = pd.read_csv(f"../data_in_processing/cluster_outputs/labels_{clus_id}.csv", index_col=[0, 1, 2])

df_edges_labels.head(10)

                                          label
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495             1
                             874              1
                             304              1
                 1495        1201             2
                             304              1
                             199              2
                             1165             1
                 874         1201             2
                             304              2
                             1585             2

In [5]:
df_edges_labels["label"].value_counts()

label
1    1038786
2     835269
0     183589
Name: count, dtype: int64

In [6]:
df = pd.read_csv(f"../data_in_processing/E1S1_scaled.csv", index_col=[0, 1])

In [7]:
df.head(10)

                           Nuclear_size  ERKKTR_ratio  FoxO3A_ratio  \
Image_Metadata_T track_id
0                1              303.000      0.704407       1.33383
                 2              268.001      1.227760       1.20592
                 3              370.000      0.779226       1.27561
                 4              341.000      0.870780       1.34460
                 5              308.000      0.807262       1.47321
                 6              350.000      0.980973       1.26054
                 7              195.000      1.256230       1.28830
                 8              290.001      0.768351       1.40894
                 9              342.000      1.169270       1.20118
                 10             281.000      0.822755       1.28673

                           objNuclei_Location_Center_X  \
Image_Metadata_T track_id
0                1                            932.2110
                 2                            162.3280
                 3                            647.8160
                 4                            642.9880
                 5                            990.7180
                 6                            584.2370
                 7                            672.4360
                 8                            488.3030
                 9                             38.3626
                 10                           716.2210

                           objNuclei_Location_Center_Y  ERKKTR_ratio_scaled  \
Image_Metadata_T track_id
0                1                            875.2480             0.239322
                 2                            365.4140             0.540105
                 3                            846.5760             0.156325
                 4                            827.8650             0.364739
                 5                             59.4675             0.161764
                 6                            814.5000             0.331472
                 7                            282.3080             0.400600
                 8                            216.4590             0.021576
                 9                            364.9940             0.118183
                 10                           840.9220             0.012737

                           FoxO3A_ratio_scaled
Image_Metadata_T track_id
0                1                    0.614450
                 2                    0.506309
                 3                    0.700809
                 4                    0.657277
                 5                    0.718735
                 6                    0.570868
                 7                    0.466161
                 8                    0.560492
                 9                    0.337490
                 10                   0.455401

# Generating Graphs

In [8]:
from scripts.Advanced_plotting_edges import save_frame

In [ ]:
for image_T in df_edges_labels.index.get_level_values(0).unique():
    save_frame(
        image_T,
        df_edges_labels.loc[image_T],
        df.loc[image_T],
        f"../outputs/pics_for_gifs_edges/{image_T}.png"
    )
    print(f"{image_T}. Done!")

0. Done!
1. Done!
2. Done!
3. Done!
4. Done!
5. Done!
6. Done!
7. Done!
8. Done!
9. Done!
10. Done!
11. Done!
12. Done!
13. Done!
14. Done!
15. Done!
16. Done!
17. Done!
18. Done!
19. Done!
20. Done!
21. Done!
22. Done!
23. Done!
24. Done!
25. Done!
26. Done!
27. Done!
28. Done!
29. Done!
30. Done!
31. Done!
32. Done!
33. Done!
34. Done!
35. Done!
36. Done!
37. Done!
38. Done!
39. Done!
40. Done!
41. Done!
42. Done!
43. Done!
44. Done!
45. Done!
46. Done!
47. Done!
48. Done!
49. Done!
50. Done!
51. Done!
52. Done!
53. Done!
54. Done!
55. Done!
56. Done!
57. Done!
58. Done!
59. Done!
60. Done!
61. Done!
62. Done!
63. Done!
64. Done!
65. Done!
66. Done!
67. Done!
68. Done!
69. Done!
70. Done!
71. Done!
72. Done!
73. Done!
74. Done!
75. Done!
76. Done!
77. Done!
78. Done!
79. Done!
80. Done!
81. Done!
82. Done!
83. Done!
84. Done!
85. Done!
86. Done!
87. Done!
88. Done!
89. Done!
90. Done!
91. Done!
92. Done!
93. Done!
94. Done!
95. Done!
96. Done!
97. Done!
98. Done!
99. Done!
100. Done!
101. Done!
102. Done!
103. Done!
104. Done!
105. Done!
106. Done!
107. Done!
108. Done!
109. Done!
110. Done!
111. Done!
112. Done!
113. Done!
114. Done!
115. Done!
116. Done!
117. Done!
118. Done!
119. Done!
120. Done!
121. Done!
122. Done!
123. Done!
124. Done!
125. Done!
126. Done!
127. Done!
128. Done!
129. Done!
130. Done!
131. Done!
132. Done!
133. Done!
134. Done!
135. Done!
136. Done!
137. Done!
138. Done!
139. Done!
140. Done!
141. Done!
142. Done!
143. Done!
144. Done!
145. Done!
146. Done!
147. Done!
148. Done!
149. Done!
150. Done!
151. Done!
152. Done!
153. Done!
154. Done!
155. Done!
156. Done!
157. Done!
158. Done!
159. Done!
160. Done!
161. Done!
162. Done!
163. Done!
164. Done!
165. Done!
166. Done!
167. Done!
168. Done!
169. Done!
170. Done!
171. Done!
172. Done!
173. Done!
174. Done!
175. Done!
176. Done!
177. Done!
178. Done!
179. Done!
180. Done!
181. Done!
182. Done!
183. Done!
184. Done!
185. Done!
186. Done!
187. Done!
188. Done!
189. Done!
190. Done!
191. Done!
192. Done!
193. Done!
194. Done!
195. Done!
196. Done!
197. Done!
198. Done!
199. Done!
200. Done!
201. Done!
202. Done!
203. Done!
204. Done!
205. Done!
206. Done!