In [2]:
import networkx as nx
import pandas as pd
import numpy as np

import sys
sys.path.append('..')

# Loading Data

In [3]:
clus_id = 3

In [4]:
df_edges_labels = pd.read_csv(f"../data_in_processing/cluster_outputs/labels_{clus_id}.csv", index_col=[0, 1, 2])

df_edges_labels.head(10)

                                          label
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495             1
                             874              1
                             304              1
                 1495        1201             2
                             304              1
                             199              2
                             1165             1
                 874         1201             2
                             304              2
                             1585             2

In [5]:
df_edges_labels["label"].value_counts()

label
1    1038786
2     835269
0     183589
Name: count, dtype: int64

In [ ]:
df_scaled_data = pd.read_csv(f"../data_in_processing/E1S1_scaled.csv", index_col=[0, 1])

In [ ]:
df_scaled_data.head(10)

                           Nuclear_size  ERKKTR_ratio  FoxO3A_ratio  \
Image_Metadata_T track_id
0                1              303.000      0.704407       1.33383
                 2              268.001      1.227760       1.20592
                 3              370.000      0.779226       1.27561
                 4              341.000      0.870780       1.34460
                 5              308.000      0.807262       1.47321
                 6              350.000      0.980973       1.26054
                 7              195.000      1.256230       1.28830
                 8              290.001      0.768351       1.40894
                 9              342.000      1.169270       1.20118
                 10             281.000      0.822755       1.28673

                           objNuclei_Location_Center_X  \
Image_Metadata_T track_id
0                1                            932.2110
                 2                            162.3280
                 3                            647.8160
                 4                            642.9880
                 5                            990.7180
                 6                            584.2370
                 7                            672.4360
                 8                            488.3030
                 9                             38.3626
                 10                           716.2210

                           objNuclei_Location_Center_Y  ERKKTR_ratio_scaled  \
Image_Metadata_T track_id
0                1                            875.2480             0.239322
                 2                            365.4140             0.540105
                 3                            846.5760             0.156325
                 4                            827.8650             0.364739
                 5                             59.4675             0.161764
                 6                            814.5000             0.331472
                 7                            282.3080             0.400600
                 8                            216.4590             0.021576
                 9                            364.9940             0.118183
                 10                           840.9220             0.012737

                           FoxO3A_ratio_scaled
Image_Metadata_T track_id
0                1                    0.614450
                 2                    0.506309
                 3                    0.700809
                 4                    0.657277
                 5                    0.718735
                 6                    0.570868
                 7                    0.466161
                 8                    0.560492
                 9                    0.337490
                 10                   0.455401

In [13]:
df_graphs_flatten = pd.read_csv(f"../data_in_processing/E1S1_graphs_flattened.csv", index_col=[0, 1, 2])

df_graphs_flatten["label"] = df_edges_labels["label"]

df_graphs_flatten.head(10)

                                          ERK_me_t0  ERK_neigh_t0  ERK_me_t1  \
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495          0.713311      0.008047   0.577748
                             874           0.713311      0.765061   0.577748
                             304           0.713311      0.004324   0.577748
                 1495        1201          0.008047      0.713311   0.002635
                             304           0.008047      0.004324   0.002635
                             199           0.008047      0.185412   0.002635
                             1165          0.008047      0.473295   0.002635
                 874         1201          0.765061      0.713311   0.802783
                             304           0.765061      0.004324   0.802783
                             1585          0.765061      0.874623   0.802783

                                          ERK_neigh_t1  ERK_me_diff  \
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495             0.002635    -0.135563
                             874              0.802783    -0.135563
                             304              0.020567    -0.135563
                 1495        1201             0.577748    -0.005412
                             304              0.020567    -0.005412
                             199              0.154744    -0.005412
                             1165             0.480243    -0.005412
                 874         1201             0.577748     0.037722
                             304              0.020567     0.037722
                             1585             0.791250     0.037722

                                          ERK_neigh_diff  label
Image_Metadata_T track_id_t0 track_id_t1
0                1201        1495              -0.005412      1
                             874                0.037722      1
                             304                0.016243      1
                 1495        1201              -0.135563      2
                             304                0.016243      1
                             199               -0.030668      2
                             1165               0.006947      1
                 874         1201              -0.135563      2
                             304                0.016243      2
                             1585              -0.083374      2

# Viewing Data

In [15]:
import matplotlib.pyplot as plt

In [1]:
def plot_data(df: pd.DataFrame, labels: list[int]|None = None, alpha = 0.05) -> None:
    fig, ax = plt.subplots(1, figsize=(10, 10))

    if labels is None:
        ax.scatter(
            df[df.columns[0]].to_numpy(),
            df[df.columns[1]].to_numpy(),
            marker='.',
            alpha = alpha,
        )
    else:
        for lab_idx in labels:
            ax.scatter(
                df[df.columns[0]].to_numpy(),
                df[df.columns[1]].to_numpy(),
                marker='.',
                alpha = alpha,
                label = f"lab{lab_idx}",
            )

    ax.set_title("Data Visualized")

    ax.set_xlabel(df.columns[0])
    ax.set_xlabel(df.columns[1])

    ax.legend()

NameError: name 'pd' is not defined

In [2]:
plot_data(
    df_graphs_flatten["ERK_me_diff ERK_neigh_diff".split(" ")], 
    labels=[lab_idx for lab_idx in df_graphs_flatten["label"].value_counts().to_dict().keys() if lab_idx not in {-1}],
    alpha = 0.01
)

NameError: name 'plot_data' is not defined

# Generating Graphs

In [9]:
from scripts.Advanced_plotting_edges import save_frame

In [10]:
# for image_T in df_edges_labels.index.get_level_values(0).unique():
#     save_frame(
#         image_T,
#         df_edges_labels.loc[image_T],
#         df.loc[image_T],
#         f"../outputs/pics_for_gifs_edges/{image_T}.png"
#     )
#     print(f"{image_T}. Done!")